In [1]:
import numpy as np

A = np.array([
    [2.6,4.8,1.8,0.9],
    [3.2,4.4,2.5,2.8],
    [2.4,3.6,3.8,2.5]
])

B = np.array([
    [3.6,2.5,3.0,2.5],
    [4.5,5.0,3.5,3.8],
    [2.9,3.0,4.6,4.0]
])

S = A + B
print(S)

[[6.2 7.3 4.8 3.4]
 [7.7 9.4 6.  6.6]
 [5.3 6.6 8.4 6.5]]
